### PR TITLE
Add more ArgumentsNValidator combinators

### PR DESCRIPTION
**Pull request by gakuzzzz**
More combinators to make it easier to handle collections, etc.

Ideally, I'd like to make it as same expressive as `forEach` in `ValidationBuilder`, but I'm working on a PR with only `List` support for now.

### CODE REVIEW

**Comment by making** [comment]
@gakuzzzz Awesome!
I rerun the script and format code. `sequence1` and `traverse1` no longer exist and tests failed.

**Comment by making** [comment]
`ArgumentsValidators.liftList` is quite useful.
Is there any way to add "index" of the violation when `liftList` returns `Validated.failure`

for example,

```java
Arguments1Validator<Iterable<String>, List<Email>> emailsValidator = ArgumentsValidators.liftList(emailValidator);
Validated<List<Email>> validated = emailsValidator.validate(Arrays.asList("foo@example.com", "barexample.com"));
System.out.println(validated.errors()); // [ConstraintViolation{name='email', messageKey='charSequence.email', defaultMessageFormat='"{0}" must be a valid email address', args=[email, barexample.com]}]
```

I expect the `ConstraintViolation` to have `email[1]` as its name rather than `email`.

**Comment by gakuzzzz** [comment]
> I expect the ConstraintViolation to have email[1] as its name rather than email.

I agree.

**Comment by gakuzzzz** [comment]
> I expect the ConstraintViolation to have email[1] as its name rather than email.

https://github.com/making/yavi/pull/134/commits/64022694f866764682f3760dfbbb4549f899a02d#diff-bab7797640abdc41cb2eecd05c360094b36e53e0e74be552f6ea8936c1cbba36R325-R327

**Comment by making** [comment]
cool

**Pull request merged**
