### PR TITLE
Fix deep nesting validation

### PR DESCRIPTION
**Pull request by ddzida**
Fix for #60

### CODE REVIEW

**Comment by making** [comment]
@ddzida Thanks for the pull request!
I'll take a look at the change after finishing gh-119 work.

**Comment by making** [comment]
Looks good to me.
Thanks for your contribution!
I couldn't find the root cause! super!

**Comment by making** [comment]
@ddzida 
I found the proposed solution is not enough. I think it covers only 3-layers nested object.

Here is an example that doesn't work as expected. Maybe a recursive approach is needed.
```java
import am.ik.yavi.builder.ValidatorBuilder;
import am.ik.yavi.core.Validator;

public class Demo {
	static class A {
		private final B b;

		public A(B b) {
			this.b = b;
		}

		public B getB() {
			return b;
		}
	}

	static class B {
		private final C c;

		public B(C c) {
			this.c = c;
		}

		public C getC() {
			return c;
		}
	}

	static class C {
		private final D d;

		public C(D d) {
			this.d = d;
		}

		public D getD() {
			return d;
		}
	}

	static class D {
		private final E e;

		public D(E e) {
			this.e = e;
		}

		public E getE() {
			return e;
		}
	}

	static class E {
		private final int value;

		public E(int value) {
			this.value = value;
		}

		public int getValue() {
			return value;
		}
	}

	public static void main(String[] args) {
		final Validator<A> validator = ValidatorBuilder.of(A.class)
				.nest(A::getB, "b",
						b1 -> b1.nest(B::getC, "c",
								b2 -> b2.nest(C::getD, "d",
										b3 -> b3.nest(D::getE, "e",
												b4 -> b4._integer(E::getValue, "value",
														c -> c.greaterThanOrEqual(100))))))
				.build();
		System.out.println(validator.validate(new A(null)).isValid()); // should be false and is false
		System.out.println(validator.validate(new A(new B(null))).isValid());  // should be false and is false
		System.out.println(validator.validate(new A(new B(new C(null)))).isValid()); // should be false and is true ???
		System.out.println(validator.validate(new A(new B(new C(new D(null))))).isValid()); // should be false and is true ???
		System.out.println(validator.validate(new A(new B(new C(new D(new E(100)))))).isValid());  // should be true and is true

	}
}
```

**Comment by ddzida** [comment]
Thanks for your feedback. I'll try to improve this solution so that it also works for n-layered nested objects.

**Comment by making** [comment]
@ddzida much appreciated 🙇‍♂️

**Comment by ddzida** [comment]
I think I found a root cause. In method `ValidationBuilder#toNestedFunction(...)` I used `toNestedValue(...)` what was wrong for n-layered nested objects (two or more layers). I've changed this in the following way:
```
private <N> Function<T, ?> toNestedFunction(Function<T, N> nested, ConstraintPredicates<N, ?> predicates) {
		if (predicates instanceof NestedConstraintPredicates) {
			return target -> {
				N nestedValue = nested.apply(target);
				if (nestedValue == null) {
					return null;
				}

				return (N) ((NestedConstraintPredicates) predicates).nestedValue(nestedValue);
			};
		}

		return nested;
	}
```
Now, it works as expected. I opened new PR for this change #123

**Pull request merged**
