### PR TITLE
reproduction test for #127

### PR DESCRIPTION
**Pull request by sis-yoshiday**
for #127

### CODE REVIEW

**Comment by making** [comment]
It could be related to the change in #123 
(cc @ddzida FYI)

**Comment by ddzida** [comment]
@making 
It is not related to the change in #123. I have checked that the bug is also before #123. It could be related to `NestedValidatorSubset`:
```
	public NestedValidatorSubset(Function<T, N> nested, ValidatorSubset<N> validator,
			String prefix) {
		this.nested = nested;
//the below line may be problematic when a validator is instance of NestedValidatorSubset, because prefix is not set_ 
		this.validator = (validator instanceof Validator)
				? ((Validator<N>) validator).prefixed(prefix)
				: validator;
	}
```

If I have some time I'll take a look at this carefully.

**Comment by making** [comment]
> //the below line may be problematic when a validator is instance of NestedValidatorSubset, because prefix is not set_ 

Thanks, Your diagnosis looks correct.
`prefix` is not propagated in case of 3+ level nest;

**Comment by making** [comment]
> `prefix` is not propagated in case of 3+ level nest;

But it works unless `constraintOnCondition` is used 🤔

**Comment by making** [comment]
> > `prefix` is not propagated in case of 3+ level nest;
> 
> But it works unless `constraintOnCondition` is used 🤔

My bad, `NestedValidatorSubset` is used only for `constraintOnCondition`

**Comment by ddzida** [comment]
I have investigate this issue and I have found a solution to solve this problem and others related with name and conditional validation.  I've created #130. I am not sure whether the proposed solution is the right direction. Please feel free to adopt or reject this change.

**Comment by making** [comment]
fixed via feb571cf6ae1e97b1d7ab086e3b07fddee27511a

**Pull request closed without merging**
