### PR TITLE
Add lift for other collections/optional

### PR DESCRIPTION
**Pull request by gakuzzzz**

### CODE REVIEW

**Comment by making** [comment]
maybe nice to have `liftCollector` ?

**Comment by gakuzzzz** [comment]
> maybe nice to have `liftCollector` ?

Hmm, I couldn't image it well.

Does it mean to lift `Arguments1Validator<A1, X>` to `Arguments1Validator<Collector<WOWOWO, ?, A1>, Collecotr<WOWOWO, ?, X>` ?

**Comment by making** [comment]
Ah, I meant `traverseCollector` you had previously proposed.

**Comment by gakuzzzz** [comment]
Ah, I see `traverseCollector`.

mmm, It's troubling.... If indexing is to be done properly, it cannot be done CONCURRENT, and the implementation may not be practical in terms of performance.

**Comment by making** [comment]
Got it. Let's include liftCollection/Set/Optional in the 0.8.0 release.

**Comment by gakuzzzz** [comment]
I'll try my best this weekend.

One point, about the method placement, in the current PR, I put it in both the instance method and the static method, which do you think is better?

1. all as static methods of `ArgumentValidators` as well as the existing `liftList`, but not providing instance methods of `ValueValidator`.

1. define them both as static methods of `ArgumentValidators` and as instance methods of `ValueValidator`.

1. define them only in the instance methods of `ValueValidator`, leaving the existing `ArgumentValidators.liftList` as `@deprecated`.

**Comment by making** [comment]
@gakuzzzz Thanks for your support.

Ideally these methods look better to be in `ValueValidator`. However, `Arguments1Validator` has `split` / `combine` method that does not exist in `ValueValidator`, and basically it is assumed that the user will use `Arguments1Validator` instead of `ValueValidator`. So I think lift methods exist in `ArgumentsValidators` (option 1).

**Comment by making** [comment]
Option 2 is also available.

**Comment by gakuzzzz** [comment]
I've got it all set up, so please review it @making.

Currently, I am choosing option 2.

I haven't been able to run the `.sh` locally, so it would be helpful if you could take a look at that as well.

**Comment by gakuzzzz** [comment]
Oops, I forgot to add the tests. I'll add them.

**Comment by gakuzzzz** [comment]
done

**Comment by making** [comment]
@gakuzzzz thanks for your work! much appreciated!

I found that there are circular references between Arguments1Validator and ArgumentsValidators. I want to avoid circular references as much as possible.

Do changes in https://github.com/making/yavi/commit/786ab09a63a602b6acad62d32832a2e8b6f6986b make sense?

I tried to keep the upper and lower bounds, but I couldn't fix the compilation error.

**Comment by making** [comment]
I'll merge this branch with https://github.com/making/yavi/pull/137/commits/865f36eb00e87bb3742d176a6159f8b2a646d5dd

**Comment by gakuzzzz** [comment]
Ops, sorry, I have been caught your comment just now!

I'll check https://github.com/making/yavi/commit/786ab09a63a602b6acad62d32832a2e8b6f6986b later!

**Comment by gakuzzzz** [comment]
mmm...

[This change](https://github.com/making/yavi/commit/865f36eb00e87bb3742d176a6159f8b2a646d5dd#diff-4179930cccfcb476cada8da3646cc8cba5901ac8d0e4e49fbfc3ad6230e9691eR355) has made the interface less flexible.

There is no reason to keep the static methods since they are no longer as expressive as the instance methods.

If this is the case, it may be better to remove all static methods and use only instance methods...

@making

**Comment by making** [comment]
> There is no reason to keep the static methods since they are no longer as expressive as the instance methods.


`ArgumentsValidators#lift****` provides the conversion from `ValueValidator` to `Arguments1Validator` (upcast) while `ApplicativeValidator#lift****` returns `ValueValidator` (downcast). 

But `Arguments1Validator.from(valueValidator.lift****())` should be fine. Maybe deprecate `ArgumentsValidators#lift****` in the next release.

**Comment by gakuzzzz** [comment]
🤔 

> ArgumentsValidators#lift**** provides the conversion from ValueValidator to Arguments1Validator (upcast) while ApplicativeValidator#lift**** returns ValueValidator (downcast).

Isn't "from  `ValueValidator` to `Arguments1Validator`" a downcast?
since `Arguments1Validator extends ValueValidator`

> `Arguments1Validator.from(valueValidator.lift****())` should be fine. Maybe deprecate `ArgumentsValidators#lift****` in the next release.

sounds good.

I am more concerned about the fact that we can no longer create a `ValueValidator<Iterable<T>, List<SuperClass>>` from a `ValueValidator<T, SubClass>`.

Similarly, we can no longer create a `ValueValidator<Iterable<SubClass>, List<A>>` from a `ValueValidator<SuperClass, A>`.

**Comment by making** [comment]
@gakuzzzz please take a look at https://github.com/making/yavi/pull/149

**Comment by making** [comment]
> Isn't "from `ValueValidator` to `Arguments1Validator`" a downcast?

yeah, it's opposite 😅 (fixed)

**Comment by gakuzzzz** [comment]
Oh, I see #149

**Pull request merged**
